package de.haniibrahim.seriallogger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author hi
 */
public class InfoDialog extends javax.swing.JDialog {

    /**
     * Creates new form InfoDialog
     * @param parent
     * @param modal
     */
    public InfoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(bt_Ok); // Set OK-Button to default    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        lb_Text1 = new javax.swing.JLabel();
        lb_copyright = new javax.swing.JLabel();
        bt_Ok = new javax.swing.JButton();
        lb_Text2 = new javax.swing.JLabel();
        lb_Image = new javax.swing.JLabel();
        lb_Text3 = new javax.swing.JLabel();
        lb_Version = new javax.swing.JLabel();
        lb_Email = new javax.swing.JLabel();
        lb_License = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Info");
        setAlwaysOnTop(true);
        setModal(true);
        setName("dlg_Info"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        lb_title.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lb_title.setText("SerialLogger");
        lb_title.setToolTipText("");

        lb_Text1.setText("Logs data received from a serial interface");

        lb_copyright.setText("(c) Hani Andreas Ibrahim - GPL 3.0");

        bt_Ok.setText("OK");
        bt_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkActionPerformed(evt);
            }
        });

        lb_Text2.setText("to GUI, console or file.");

        lb_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/haniibrahim/seriallogger/serial_th.png"))); // NOI18N

        lb_Text3.setText("Version: ");

        lb_Version.setText("NO VERSION");

        lb_Email.setText("hani.ibrahim@gmx.de");

        lb_License.setText("GNU Public License 3.0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(bt_Ok, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lb_Image)
                                    .add(layout.createSequentialGroup()
                                        .add(lb_Text3)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(lb_Version))))
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(lb_copyright))
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lb_Text2)
                                    .add(lb_Text1)
                                    .add(lb_title)))
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lb_Email)
                                    .add(lb_License))))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lb_Image)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lb_title)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_Text1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_Text2)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lb_Text3)
                    .add(lb_Version))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 58, Short.MAX_VALUE)
                .add(lb_copyright)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_License)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_Email)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bt_Ok)
                .add(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_OkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Ok;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_Image;
    private javax.swing.JLabel lb_License;
    private javax.swing.JLabel lb_Text1;
    private javax.swing.JLabel lb_Text2;
    private javax.swing.JLabel lb_Text3;
    private javax.swing.JLabel lb_Version;
    private javax.swing.JLabel lb_copyright;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
