package de.haniibrahim.seriallogger;

import java.util.Calendar;
import java.util.Date;

/**
 * Info Dialogbox
 * @author hi
 */
public class InfoDialog extends javax.swing.JDialog {
    
    private String version = "1.0.0"; // CHANGE VERSION NUMBER AS NECESSARY - Shown in Infodialog()
    
    /**
     * Creates new form InfoDialog
     * @param parent
     * @param modal
     */
    public InfoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lb_Version.setText(version); // Set version no.
        lb_copyright.setText("© 2013 - " + getCurrentYear());
        this.getRootPane().setDefaultButton(bt_Ok); // Set OK-Button to default    
    }
    
    /**
     * Get current year as integer
     * @return int current year (YYYY)
     */
    private static int getCurrentYear(){
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        int jahr = cal.get(Calendar.YEAR);
        return jahr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        lb_Text1 = new javax.swing.JLabel();
        lb_copyright = new javax.swing.JLabel();
        bt_Ok = new javax.swing.JButton();
        lb_Text2 = new javax.swing.JLabel();
        lb_Image = new javax.swing.JLabel();
        lb_Label_version = new javax.swing.JLabel();
        lb_Version = new javax.swing.JLabel();
        lb_Email = new javax.swing.JLabel();
        lb_License = new javax.swing.JLabel();
        lb_copyright1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Info");
        setAlwaysOnTop(true);
        setModal(true);
        setName("dlg_Info"); // NOI18N
        setResizable(false);

        lb_title.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lb_title.setText("SerialLogger");
        lb_title.setToolTipText("");

        lb_Text1.setText("Logs data received from a serial interface");

        lb_copyright.setText("COPYRIGHT");

        bt_Ok.setText("OK");
        bt_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkActionPerformed(evt);
            }
        });

        lb_Text2.setText("to GUI, console or file.");

        lb_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/haniibrahim/seriallogger/serial_th.png"))); // NOI18N

        lb_Label_version.setText("Version: ");

        lb_Version.setText("NO VERSION");

        lb_Email.setText("hani.ibrahim@gmx.de");

        lb_License.setText("GNU Public License 3.0");

        lb_copyright1.setText("Hani A. Ibrahim");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lb_Image)
                    .add(layout.createSequentialGroup()
                        .add(lb_Label_version)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lb_Version))
                    .add(lb_copyright)
                    .add(lb_Text2)
                    .add(lb_Text1)
                    .add(lb_title)
                    .add(lb_copyright1)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(132, 132, 132)
                            .add(bt_Ok, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(lb_Email)
                        .add(lb_License)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lb_Image)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lb_title)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_Text1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_Text2)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lb_Label_version)
                    .add(lb_Version))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(lb_copyright)
                .add(1, 1, 1)
                .add(lb_copyright1)
                .add(18, 18, 18)
                .add(lb_License)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_Email)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bt_Ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * OK button event
     * @param evt 
     */
    private void bt_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_OkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Ok;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_Image;
    private javax.swing.JLabel lb_Label_version;
    private javax.swing.JLabel lb_License;
    private javax.swing.JLabel lb_Text1;
    private javax.swing.JLabel lb_Text2;
    private javax.swing.JLabel lb_Version;
    private javax.swing.JLabel lb_copyright;
    private javax.swing.JLabel lb_copyright1;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
