/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.haniibrahim.seriallogger;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HI
 */
public class Options extends javax.swing.JDialog {

    private final int lafNum = UIManager.getInstalledLookAndFeels().length; // Amount of available LaFs
    private final UIManager.LookAndFeelInfo[] lafClasses = new UIManager.LookAndFeelInfo[lafNum]; // LaF classes
//    private final UIManager.LookAndFeelInfo[] lafNames = new UIManager.LookAndFeelInfo[lafNum]; // Laf names
    private final String[] lafNamesStr = new String[lafNum]; // LaF names as Strings
    private final int lafIdx;

    /**
     * Creates new form Options
     *
     * @param parent
     * @param modal
     */
    public Options(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Get and put Look and Feels
        setAvailableLafClasses(); // set class variable lafClasses
        setAvailableLafNames();   // set class variable lafNames
        putLafNames(); // put LaF to combobox

        // 
        lafIdx = Arrays.asList(lafNamesStr).indexOf(getCurrentLaf()); // Get index of current LaF of LaF-list
        cb_LookAndFeel.setSelectedIndex(lafIdx); // Set curemnt LaF in combobox

//        cb_LookAndFeel.setSelectedItem(getCurrentLaf()); // set combobox entry to current LaF
        myInit();
    }
    
    //-------------------------------------------------------------------------

    /**
     * Getter for LaF classes
     *
     * @return LaF classes
     */
    public UIManager.LookAndFeelInfo[] getLafClasses() {
        return this.lafClasses;
    }

    /**
     * Getter for LaF index number of current LaF
     *
     * @return Index number of current LaF
     */
    public int getLafIdx() {
        return this.lafIdx;
    }
    
    // ------------------------------------------------------------------------
    
    /**
     * My presets for the GUI
     */
    private void myInit() {
        this.getRootPane().setDefaultButton(bt_OK); // Set OK-Button to default   
    }

//    private void putAvailableLaF(){
//        cb_LookAndFeel.removeAllItems();
//        for (UIManager.LookAndFeelInfo laf : UIManager.getInstalledLookAndFeels()){
//            cb_LookAndFeel.addItem(laf.getClassName());
//        }
//    }
    
    /**
     * Fill up the class var lafClasses with the classes of LaFs
     */
    private void setAvailableLafClasses() {
        int i = 0;
        for (UIManager.LookAndFeelInfo laf : UIManager.getInstalledLookAndFeels()) {
            lafClasses[i] = laf;
            i++;
        }
    }

    /**
     * Fill up the class var lafNames with names of LaFs
     */
    private void setAvailableLafNames() {
        int i = 0;
        for (UIManager.LookAndFeelInfo laf : UIManager.getInstalledLookAndFeels()) {
//            lafNames[i] = laf;
            lafNamesStr[i] = laf.getName();
            i++;
        }
    }

    /**
     * Set List of Look and Feels to the combobox in the Options dialog
     */
    private void putLafNames() {
        cb_LookAndFeel.removeAllItems();
        for (int i = 0; i < lafNum; i++) {
            cb_LookAndFeel.addItem(lafClasses[i].getName());
        }
    }

    /**
     * Get cuurent Look and Feel
     *
     * @return Look and Feel
     */
    private String getCurrentLaf() {
        return UIManager.getLookAndFeel().getName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_Options = new javax.swing.JTabbedPane();
        pn_Appearance = new javax.swing.JPanel();
        lb_LookAndFeel = new javax.swing.JLabel();
        cb_LookAndFeel = new javax.swing.JComboBox();
        bt_Cancel = new javax.swing.JButton();
        bt_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setModal(true);
        setName("dialogOptions"); // NOI18N
        setResizable(false);

        lb_LookAndFeel.setText("Look and Feel:");

        cb_LookAndFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pn_AppearanceLayout = new javax.swing.GroupLayout(pn_Appearance);
        pn_Appearance.setLayout(pn_AppearanceLayout);
        pn_AppearanceLayout.setHorizontalGroup(
            pn_AppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_AppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_AppearanceLayout.createSequentialGroup()
                        .addComponent(lb_LookAndFeel)
                        .addGap(0, 204, Short.MAX_VALUE))
                    .addComponent(cb_LookAndFeel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_AppearanceLayout.setVerticalGroup(
            pn_AppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_LookAndFeel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_LookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        tp_Options.addTab("Appearance", pn_Appearance);

        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });

        bt_OK.setToolTipText("");
        bt_OK.setActionCommand("Ok");
        bt_OK.setLabel("OK");
        bt_OK.setOpaque(false);
        bt_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp_Options)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Cancel)
                    .addComponent(bt_OK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_OK.getAccessibleContext().setAccessibleName("Ok");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_CancelActionPerformed

    private void bt_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OKActionPerformed
        try {
            int x = cb_LookAndFeel.getSelectedIndex();
            UIManager.setLookAndFeel(lafClasses[x].getClassName());
            SwingUtilities.updateComponentTreeUI(SerialLogger.getFrames()[0]);
            SerialLogger.getFrames()[0].pack();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_bt_OKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_OK;
    private javax.swing.JComboBox cb_LookAndFeel;
    private javax.swing.JLabel lb_LookAndFeel;
    private javax.swing.JPanel pn_Appearance;
    private javax.swing.JTabbedPane tp_Options;
    // End of variables declaration//GEN-END:variables
}
