/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.haniibrahim.seriallogger;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * JDialog where the Look and Feels can be set
 *
 * @author HI
 */
public class Options extends javax.swing.JDialog {

    private static final UIManager.LookAndFeelInfo[] lafs = LafHelper.getLafs(); // LaF classes
    private static final String[] lafNames = LafHelper.getLafNames(); // LaF names as Strings
    private static int lafIdx;
    
    /**
     * Creates new form Options
     *
     * @param parent Parent element/frame
     * @param modal Dialog modal or not
     */
    public Options(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Get and put Look and Feels
        fillInLafNames(); // put LaF to combobox

        lafIdx = Arrays.asList(lafNames).indexOf(LafHelper.getCurrentLafName()); // Get index of current LaF of LaF-list
        cb_LookAndFeel.setSelectedIndex(lafIdx); // Set curemnt LaF in combobox

        myInit();
    }

    /**
     * My presets for the GUI
     */
    private void myInit() {
        this.getRootPane().setDefaultButton(bt_OK); // Set OK-Button to default
        addEscapeListener(this); // Close dialog when ESC is pressed
    }

    /**
     * Set List of Look and Feels to the combobox in the Options dialog
     */
    private void fillInLafNames() {
        cb_LookAndFeel.removeAllItems();
        for (int i = 0; i < LafHelper.LAF_LENGTH; i++) {
            cb_LookAndFeel.addItem(lafs[i].getName());
        }
    }

    /**
     * Close dialog when ESC is pressed
     *
     * @param dialog Dialog frame which should be close by ESC
     */
    public static void addEscapeListener(final JDialog dialog) {
        ActionListener escListener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //dialog.setVisible(false);
                dialog.dispose();
            }
        };

        dialog.getRootPane().registerKeyboardAction(escListener,
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tp_Options = new javax.swing.JTabbedPane();
        pn_Appearance = new javax.swing.JPanel();
        lb_LookAndFeel = new javax.swing.JLabel();
        cb_LookAndFeel = new javax.swing.JComboBox();
        bt_Cancel = new javax.swing.JButton();
        bt_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setModal(true);
        setName("dialogOptions"); // NOI18N
        setResizable(false);

        lb_LookAndFeel.setText("Look and Feel:");

        cb_LookAndFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pn_AppearanceLayout = new javax.swing.GroupLayout(pn_Appearance);
        pn_Appearance.setLayout(pn_AppearanceLayout);
        pn_AppearanceLayout.setHorizontalGroup(
            pn_AppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_AppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_AppearanceLayout.createSequentialGroup()
                        .addComponent(lb_LookAndFeel)
                        .addGap(0, 204, Short.MAX_VALUE))
                    .addComponent(cb_LookAndFeel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_AppearanceLayout.setVerticalGroup(
            pn_AppearanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AppearanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_LookAndFeel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_LookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        tp_Options.addTab("Appearance", pn_Appearance);

        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });

        bt_OK.setText("OK");
        bt_OK.setToolTipText("");
        bt_OK.setActionCommand("OK");
        bt_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tp_Options)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_OK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Cancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Cancel)
                    .addComponent(bt_OK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_CancelActionPerformed

    private void bt_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OKActionPerformed
        try {
            int x = cb_LookAndFeel.getSelectedIndex();
            UIManager.setLookAndFeel(lafs[x].getClassName());
            SwingUtilities.updateComponentTreeUI(SerialLogger.getFrames()[0]);
            SerialLogger.getFrames()[0].pack();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_bt_OKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_OK;
    private javax.swing.JComboBox cb_LookAndFeel;
    private javax.swing.JLabel lb_LookAndFeel;
    private javax.swing.JPanel pn_Appearance;
    private javax.swing.JTabbedPane tp_Options;
    // End of variables declaration//GEN-END:variables
}
